services:
  puzzle:
    build: .
    image: 15-puzzle:latest
    stdin_open: true
    tty: true
    container_name: 15-puzzle-game
    volumes:
      - ./saves:/app/saves

  test:
    build: .
    image: 15-puzzle:latest
    container_name: 15-puzzle-test
    command: vendor/bin/phpunit
    volumes:
      - ./:/app
