services:
  puzzle:
    build: .
    image: 15-puzzle:latest
    stdin_open: true
    tty: true
    container_name: 15-puzzle-game

# TODO: figure out how to remove container not only when game ends, but when you disconnect from a container